openapi: 3.0.0
info:
  title: Auto Prioritize Service
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /stories:
    get:
      summary: List stories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  stories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Story'
  /webhook:
    post:
      summary: Receive webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [event, item]
              properties:
                event:
                  type: string
                  enum: ['item_added']
                item:
                  oneOf:
                    - $ref: '#/components/schemas/Story'
                    - type: array
                      items:
                        $ref: '#/components/schemas/Story'
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis:
                    oneOf:
                      - $ref: '#/components/schemas/Analysis'
                      - type: array
                        items:
                          $ref: '#/components/schemas/Analysis'
                  summary:
                    type: string
        '400':
          description: Invalid payload
components:
  schemas:
    Story:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
    Analysis:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        refinedDescription:
          type: string
        priority:
          type: string
          enum: [P1, P2, P3]
        acceptanceCriteria:
          type: array
          items:
            type: string
          minItems: 3
          maxItems: 6
        testCases:
          type: array
          items:
            type: string
          minItems: 3
